//! DHCPv6 option 56 — NTP Server Option (RFC 5908).
//!
//! Collects NTP server addresses / FQDNs from every non-expired lease and
//! writes a chrony `include`-able config fragment to
//! `/etc/chrony/conf.d/custom_dhcpv6.conf`.
//!
//! If any network interface has *no* active DHCPv6 lease the default server
//! list is also appended so the host always has something to sync against.

use super::OptionHandler;
use crate::lease::Lease;
use anyhow::{Context, Result};
use std::collections::HashSet;
use std::net::Ipv6Addr;

pub const OPTION_CODE: u16 = 56;
const OUTPUT_PATH: &str = "/etc/chrony/conf.d/custom_dhcpv6.conf";

// RFC 5908 NTP suboption type codes
const NTP_SUBOPTION_SRV_ADDR: u16 = 1;
const NTP_SUBOPTION_MC_ADDR: u16 = 2;
const NTP_SUBOPTION_SRV_FQDN: u16 = 3;

/// Servers used when one or more interfaces have no active DHCP lease.
const DEFAULT_SERVERS: &[&str] = &[
    "server time.cloudflare.com iburst minpoll 0 maxpoll 6 presend 2 xleave polltarget 16",
    "server time.google.com iburst minpoll 0 maxpoll 6 presend 2 xleave polltarget 16",
    "server ntp1.net.berkeley.edu iburst minpoll 0 maxpoll 6 presend 2 xleave polltarget 16",
    "server ntp2.net.berkeley.edu iburst minpoll 0 maxpoll 6 presend 2 xleave polltarget 16",
    "server time.facebook.com iburst minpoll 0 maxpoll 6 presend 2 xleave polltarget 16",
    "server time.nist.gov iburst minpoll 0 maxpoll 6 presend 2 xleave polltarget 16",
    "server clock.sjc.he.net iburst minpoll 0 maxpoll 6 presend 2 xleave polltarget 16",
    "server clock.fmt.he.net iburst minpoll 0 maxpoll 6 presend 2 xleave polltarget 16",
    "server 2.pool.ntp.org iburst minpoll 0 maxpoll 6 presend 2 xleave polltarget 16",
];

// ─────────────────────────────────────────────────────────────────────────────
// Handler
// ─────────────────────────────────────────────────────────────────────────────

pub struct NtpHandler;

impl OptionHandler for NtpHandler {
    fn option_code(&self) -> u16 {
        OPTION_CODE
    }
    fn name(&self) -> &str {
        "NTP Server Option (RFC 5908)"
    }

    fn process(&self, leases: &[Lease], all_interfaces: &[String]) -> Result<()> {
        // Interfaces that have at least one non-expired lease
        let active_ifaces: HashSet<&str> = leases
            .iter()
            .filter(|l| !l.is_expired())
            .map(|l| l.interface.as_str())
            .collect();

        // Interfaces with *no* valid lease → include defaults
        let unmanaged: Vec<&str> = all_interfaces
            .iter()
            .map(String::as_str)
            .filter(|iface| !active_ifaces.contains(iface))
            .collect();

        let include_defaults = !unmanaged.is_empty();
        if include_defaults {
            log::info!(
                "Interfaces without an active DHCPv6 lease (defaults will be added): {:?}",
                unmanaged
            );
        }

        // Collect unique NTP server lines from all non-expired leases
        let mut server_lines: Vec<String> = Vec::new();
        let mut seen: HashSet<String> = HashSet::new();

        for lease in leases.iter().filter(|l| !l.is_expired()) {
            if let Some(data) = lease.options.get(&OPTION_CODE) {
                for server in parse_ntp_option_data(data) {
                    let line = format!(
                        "server {} iburst minpoll 0 maxpoll 6 presend 2 xleave polltarget 60",
                        server
                    );
                    if seen.insert(line.clone()) {
                        log::debug!("NTP server from {}: {}", lease.interface, server);
                        server_lines.push(line);
                    }
                }
            }
        }

        // Build config text
        let mut cfg = String::from(
            "# Auto-generated by dhcpv6-option-handler — do not edit by hand.\n\
             # DHCPv6 option 56 (NTP, RFC 5908)\n\n",
        );

        if !server_lines.is_empty() {
            cfg.push_str("# DHCP-provided NTP servers\n");
            for line in &server_lines {
                cfg.push_str(line);
                cfg.push('\n');
            }
        }

        if include_defaults || server_lines.is_empty() {
            if !server_lines.is_empty() {
                cfg.push('\n');
            }
            cfg.push_str(
                "# Default NTP servers\
                 (included because one or more interfaces have no DHCPv6 lease)\n",
            );
            for &s in DEFAULT_SERVERS {
                cfg.push_str(s);
                cfg.push('\n');
            }
        }

        // Write output
        if let Some(parent) = std::path::Path::new(OUTPUT_PATH).parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("Creating directory {:?}", parent))?;
        }
        std::fs::write(OUTPUT_PATH, &cfg)
            .with_context(|| format!("Writing {}", OUTPUT_PATH))?;

        log::info!(
            "Wrote {} DHCP-provided + {} default NTP server(s) to {}",
            server_lines.len(),
            if include_defaults || server_lines.is_empty() {
                DEFAULT_SERVERS.len()
            } else {
                0
            },
            OUTPUT_PATH
        );
        Ok(())
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Option 56 data parsing
// ─────────────────────────────────────────────────────────────────────────────

/// Parse the raw bytes of DHCPv6 option 56 into a list of server identifiers.
///
/// Three wire formats are handled, in order of preference:
/// 1. RFC 5908 suboptions (TLV with types 1/2/3).
/// 2. Raw concatenated 16-byte IPv6 addresses (some simple DHCP servers emit this).
/// 3. UTF-8 string with space/comma-separated addresses or FQDNs.
fn parse_ntp_option_data(data: &[u8]) -> Vec<String> {
    // Try RFC 5908 suboption format first
    if let Some(servers) = parse_rfc5908(data) {
        return servers;
    }

    // Fall back: concatenated 16-byte IPv6 addresses
    if !data.is_empty() && data.len() % 16 == 0 {
        let servers: Vec<String> = data
            .chunks_exact(16)
            .map(|chunk| {
                let octets: [u8; 16] = chunk.try_into().expect("chunks_exact guarantees 16 bytes");
                Ipv6Addr::from(octets).to_string()
            })
            .collect();
        if !servers.is_empty() {
            return servers;
        }
    }

    // Last resort: UTF-8 string
    if let Ok(s) = std::str::from_utf8(data) {
        return s
            .split(|c: char| c == ' ' || c == ',')
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .map(String::from)
            .collect();
    }

    Vec::new()
}

/// Attempt to decode data as RFC 5908 suboptions.
///
/// Returns `None` if the data is not well-formed RFC 5908 (so the caller can
/// fall back to a simpler format).
fn parse_rfc5908(data: &[u8]) -> Option<Vec<String>> {
    let mut pos = 0usize;
    let mut servers = Vec::new();

    while pos + 4 <= data.len() {
        let subtype = u16::from_be_bytes([data[pos], data[pos + 1]]);
        let sublen = u16::from_be_bytes([data[pos + 2], data[pos + 3]]) as usize;
        pos += 4;

        if pos + sublen > data.len() {
            // Length overruns the buffer → not valid RFC 5908
            return None;
        }

        let sub_data = &data[pos..pos + sublen];

        match subtype {
            NTP_SUBOPTION_SRV_ADDR | NTP_SUBOPTION_MC_ADDR => {
                if sublen != 16 {
                    // Address suboptions must be exactly 16 bytes
                    return None;
                }
                let octets: [u8; 16] = sub_data.try_into().ok()?;
                servers.push(Ipv6Addr::from(octets).to_string());
            }
            NTP_SUBOPTION_SRV_FQDN => {
                if let Some(fqdn) = decode_dns_wire_name(sub_data) {
                    servers.push(fqdn);
                }
            }
            _ => {
                // Unknown future suboption — skip, per RFC
            }
        }

        pos += sublen;
    }

    // Only accept if we consumed exactly all the bytes
    if pos != data.len() {
        return None;
    }

    if servers.is_empty() {
        None
    } else {
        Some(servers)
    }
}

/// Decode a DNS wire-format name (`\x03foo\x03bar\x00`) into a dotted string.
fn decode_dns_wire_name(data: &[u8]) -> Option<String> {
    let mut labels: Vec<String> = Vec::new();
    let mut pos = 0usize;

    while pos < data.len() {
        let label_len = data[pos] as usize;
        pos += 1;
        if label_len == 0 {
            break; // root label
        }
        if pos + label_len > data.len() {
            return None;
        }
        let label = std::str::from_utf8(&data[pos..pos + label_len]).ok()?;
        labels.push(label.to_string());
        pos += label_len;
    }

    if labels.is_empty() {
        None
    } else {
        Some(labels.join("."))
    }
}
